const KNOWN_ACRONYMS = new Set([
  "TNI", "AL", "KRI", "NATO", "G2G", "MRO", "POL", "PKR", "CMS", "BAPHP", "SP2D", "DIPA", "ZEE", "ALKI",
  "VIP", "CASREP", "COA", "HCM", "IDR", "USD", "EUR", "ASW", "RTB", "LPD", "PNS", "DEFCON", "ISO",
  "KPPN", "SAR", "WIA", "KIA", "APBN", "PBB", "UN", "BNPB", "KPLP", "BAKAMLA", "DISBEKAL", "DISLAIKMATAL",
  "FASHARKAN", "SRENA", "SOPS", "SLOG", "SPERS", "SPOTMAR", "DEPOPS", "DEPSIN", "DEPLOG",
  "DEPSENAU", "KLD", "KLS", "KLK", "KOPDA", "KOPTU", "KOPKA", "SERDA", "SERTU",
  "SERKA", "SERMA", "PELDA", "PELTU", "A", "B", "AB", "O", "P", "T", "E", "S", "M", "K", "KH", "PM"
]);

const ROMAN_NUMERALS = new Set(["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]);

export const snakeToTitleCase = (value: string): string =>
  value
    ?.replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase()) ?? "";

export const snakeToLowerCaseSentence = (value: string): string =>
  value?.replace(/_/g, " ").toLowerCase() ?? "";

export const formatEnumLabel = (val: string | null | undefined): string => {
  if (!val || typeof val !== "string") return val ? String(val) : "-";

  // Handle readiness categories like C-1, C-2, C-3, C-4
  if (/^C-\d+$/i.test(val)) return val.toUpperCase();

  // If already contains spaces and no underscores, return as is
  if (!val.includes("_") && val.includes(" ")) return val;

  // If it's a known single-word acronym or roman numeral
  const upperVal = val.toUpperCase();
  if (KNOWN_ACRONYMS.has(upperVal) || ROMAN_NUMERALS.has(upperVal)) {
    return upperVal;
  }

  return val
    .split("_")
    .filter(Boolean)
    .map((word) => {
      const upper = word.toUpperCase();
      if (KNOWN_ACRONYMS.has(upper) || ROMAN_NUMERALS.has(upper)) return upper;
      if (word.length === 0) return "";
      return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
    })
    .join(" ");
};

export const KNOWN_ENUM_VALUES: Set<string> = new Set([
  "A",
  "AB",
  "ACTIVE",
  "AIRCRAFT",
  "AIR_CARGO",
  "AIR_DEFENSE",
  "ALARM",
  "ALUTSISTA",
  "AMMO_BOX",
  "AMMO_DEPOT",
  "AMMUNITION",
  "AMMUNITION_BUNKER",
  "ANNUAL_DOCKING",
  "APPROVAL",
  "APPROVED",
  "ARCHIVED",
  "ASSESSED",
  "ASSET",
  "ASSET_CAPITALIZATION",
  "ASW_SCREEN",
  "AUXILIARY",
  "AVAILABLE",
  "AVTUR_JET_A1",
  "AWARDED",
  "B",
  "B35_NAVAL",
  "BANK_TRANSFER",
  "BASE_TRANSFER",
  "BERTHED",
  "BERTHING_REST",
  "BERTH_JETTY",
  "BIASA",
  "BINTARA",
  "BOX",
  "BREVET",
  "BUDDHA",
  "C-1",
  "C-2",
  "C-3",
  "C-4",
  "CANCELLED",
  "CARGO_BARGE",
  "CASH",
  "CASREP_DEFECT",
  "CAT1",
  "CAT2",
  "CAT3",
  "CAT4",
  "CERTIFICATION",
  "CERT_KELAIKAN",
  "CLOSED",
  "COLD_STORAGE",
  "COMBAT_PATROL",
  "COMBAT_RISK",
  "COMBAT_STATION",
  "COMMAND_OFFICER",
  "COMMAND_POST",
  "COMMENDATION",
  "COMMITTED",
  "COMPLETED",
  "COMPONENT",
  "CONDEMNED",
  "CONSUMABLES",
  "CONTRACT_AGREEMENT",
  "CORRECTIVE",
  "CORVETTE",
  "COUNTER_PIRACY",
  "CRANE_INSPECTION",
  "CRATE",
  "CREATE",
  "CREW_SHORTAGE",
  "CRITICAL",
  "CRITICAL_SAFETY",
  "CRITICAL_SPARE_DEFICIT",
  "DAMAGE",
  "DAMAGED_RTB",
  "DAMAGE_CONTROL",
  "DECEASED",
  "DECOMMISSIONED",
  "DEFCON_1",
  "DEFCON_2",
  "DEFCON_3",
  "DEFCON_4",
  "DEFCON_5",
  "DEGRADED",
  "DELETE",
  "DELIVERED",
  "DEPLOG",
  "DEPLOYED",
  "DEPOPS",
  "DEPOT",
  "DEPOT_DISPATCH",
  "DEPOT_LEVEL",
  "DEPSENAU",
  "DEPSIN",
  "DIPLOMACY",
  "DIRECT_APPOINTMENT",
  "DISBEKAL",
  "DISLAIKMATAL",
  "DOCKED",
  "DOCKING",
  "DOCK_GATE_OVERHAUL",
  "DRAFT",
  "DREDGING_ALUR",
  "DRUM",
  "E",
  "EDUCATION",
  "ELECTRICAL",
  "EMBARKATION",
  "EMERGENCY",
  "EMERGENCY_AIRDROP",
  "ENGINEERING_CONTROL_ROOM",
  "EQUIPMENT",
  "EQUITY",
  "ESCORT_SURFACE",
  "EVALUATING",
  "EXPENSE",
  "EXPIRED_KELAIKAN",
  "EXPIRY",
  "EXPORT",
  "FACILITY",
  "FASHARKAN",
  "FAST_ATTACK",
  "FEMALE",
  "FENDER_REPLACEMENT",
  "FINANCE_OFFICER",
  "FLAGSHIP",
  "FLEET",
  "FLEET_RESUPPLY",
  "FLOATING_DOCK",
  "FRIGATE",
  "FUEL_DEPOT",
  "FUEL_ENERGY",
  "FUEL_STORAGE",
  "FULLY_MISSION_CAPABLE",
  "G2G",
  "GENERAL_SUPPLIES",
  "GRAVING_DOCK",
  "HEADQUARTERS",
  "HIGH",
  "HIGH_SEA",
  "HINDU",
  "HSD_MILSPEC",
  "INITIALIZE",
  "INSPECTED",
  "INVENTORY",
  "INV_MATERIAL",
  "IN_PROGRESS",
  "IN_REPAIR",
  "IN_TRANSIT",
  "ISLAM",
  "ISO_CONTAINER",
  "ISSUED",
  "JOINT_EXERCISE",
  "K",
  "KAPTEN_LAUT",
  "KATOLIK",
  "KG",
  "KH",
  "KIA",
  "KLD",
  "KLK",
  "KLS",
  "KOLONEL_LAUT",
  "KOMANDO",
  "KONGHUCU",
  "KOPDA",
  "KOPKA",
  "KOPTU",
  "KPPN_TREASURY",
  "KRI_COMMANDER",
  "LAKSAMANA_MADYA_TNI",
  "LAKSAMANA_MUDA_TNI",
  "LAKSAMANA_PERTAMA_TNI",
  "LAKSAMANA_TNI",
  "LANAL",
  "LAND_TRUCK",
  "LANTAMAL",
  "LETDA_LAUT",
  "LETKOL_LAUT",
  "LETTU_LAUT",
  "LIABILITY",
  "LIMITED_TENDER",
  "LITER",
  "LOADING",
  "LOGIN",
  "LOGISTICS_OFFICER",
  "LOGISTICS_SUPPORT",
  "LOGISTIC_REPLENISHMENT",
  "LOGOUT",
  "LOW",
  "LPD",
  "M",
  "MAINTENANCE",
  "MAINTENANCE_OFFICER",
  "MALE",
  "MAYOR_LAUT",
  "MEDIUM",
  "METER",
  "MISSION_DEPLOYMENT",
  "MISSION_ESSENTIAL",
  "MODERNIZATION",
  "MRO",
  "MRO_EQUIPMENT",
  "MRO_REPAIR",
  "MRO_SERVICE",
  "MRO_SHIP",
  "MRO_WORK_ORDER",
  "MUTATION",
  "NATO_SECRET",
  "NAVAL_AUXILIARY_VESSEL",
  "NAVIGATION",
  "NON_MISSION_CAPABLE",
  "NON_OPERATIONAL",
  "NORMAL",
  "O",
  "OCCUPIED",
  "ON_LEAVE",
  "ON_MISSION",
  "OPEN_TENDER",
  "OPERATING_MANUAL",
  "OPERATIONAL",
  "OPERATOR",
  "P",
  "PAID",
  "PALLET",
  "PAMA",
  "PAMEN",
  "PARTIAL",
  "PARTIALLY_MISSION_CAPABLE",
  "PARTIAL_RECEIVED",
  "PATI",
  "PATROL",
  "PAYROLL",
  "PELDA",
  "PELTU",
  "PENDING",
  "PENDING_VERIF",
  "PERSONNEL_OFFICER",
  "PLANNED",
  "PLANNING",
  "PM",
  "PNS_TNI",
  "PREVENTIVE",
  "PROCUREMENT",
  "PROC_CONTRACT",
  "PROMOTION",
  "PROPULSION",
  "PROTESTAN",
  "PUBLISHED",
  "RAHASIA",
  "RAHASIA_NEGARA",
  "REALISED",
  "RECEIVED",
  "REGULAR",
  "REJECTED",
  "RELIEVED",
  "REPAIR_DOCKING",
  "RESTRICTED",
  "RETIRED",
  "REVENUE",
  "REVIEW",
  "ROUTINE",
  "S",
  "SALVAGE",
  "SANGAT_RAHASIA",
  "SAR_HUMANITARIAN",
  "SCHEDULED",
  "SEAMANSHIP",
  "SENSOR_RADAR",
  "SERDA",
  "SERKA",
  "SERMA",
  "SERTU",
  "SERVICEABLE",
  "SET",
  "SHIPBOARD_STORE",
  "SHIP_UNIT",
  "SHORE_BASE",
  "SHORE_DEPOT",
  "SHORE_POWER_CALIB",
  "SHORE_POWER_STATION",
  "SIAGA_1",
  "SIGNED",
  "SLOG",
  "SOPS",
  "SPARE_PARTS",
  "SPECIALIZATION",
  "SPECIAL_DOCKING",
  "SPERS",
  "SPOTMAR",
  "SQUADRON",
  "SRENA",
  "STAKES_I",
  "STAKES_II",
  "STAKES_III",
  "STAKES_IV",
  "STANDARD_CONVOY",
  "STANDBY",
  "STOCK_OPNAME_VARIANCE",
  "STRATEGIC_RESERVE",
  "SUBMARINE",
  "SUBSYSTEM",
  "SUPERSEDED",
  "SUPER_ADMIN",
  "SUSPENDED",
  "SYSTEM",
  "T",
  "TAMTAMA",
  "TECHNICAL_SPARES",
  "TERBATAS",
  "TERMINATED",
  "TON",
  "UNCLASSIFIED",
  "UNDER_CONSTRUCTION",
  "UNESCORTED",
  "UNIT",
  "UNPAID",
  "UNSERVICEABLE",
  "UPDATE",
  "URGENT",
  "VERIFIED",
  "VIGOUR_A",
  "VIGOUR_B",
  "VIP_CEREMONY",
  "WAITING_PARTS",
  "WARNING",
  "WARSHIP_ESCORT",
  "WEAPON",
  "WIA",
  "WIRING_DIAGRAM",
  "WORKSHOP_FASHARKAN",
  "WORK_ORDER_CREATED"
]);
